version: '3.7'

services:

  traefik:
    image: "traefik:v${TRAEFIK_VERSION}"
    container_name: "${PREFIX}-traefik"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command: |-
      --providers.docker.network="${PREFIX}-network"
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.entrypoints: https
      traefik.http.routers.traefik.rule: Host(`traefik.${DOCKER_DOMAIN}`,`dashboard.traefik.me`)
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.tls: "true"
      traefik.http.services.traefik.loadbalancer.server.port: 8080

      # catchall router
      traefik.http.routers.http-catchall.rule: "HostRegexp(`{subdomain:[A-Za-z0-9-]+}.${DOCKER_DOMAIN}`,`{subdomain:[A-Za-z0-9-]+}.traefik.me`)"
      traefik.http.routers.http-catchall.entrypoints: "http"
      traefik.http.routers.http-catchall.middlewares: "redirect-to-https"

      # middleware redirect
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/traefik.dynamic.yml:/configuration/traefik.dynamic.yml
      - ./certs:/ssl # mkcert certs

  portainer:
    image: "portainer/portainer-ce:${PORTAINER_VERSION}-alpine"
    container_name: "${PREFIX}-portainer"
    restart: unless-stopped
    command: |-
      -H unix:///var/run/docker.sock
      --logo "${LOGO_URL}"
      --admin-password-file /tmp/portainer_password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_admin_password:/tmp/portainer_password
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.entrypoints: https
      traefik.http.routers.portainer.rule: Host(`portainer.${DOCKER_DOMAIN}`,`portainer.traefik.me`)
      traefik.http.routers.portainer.tls: "true"
      traefik.http.services.portainer.loadbalancer.server.port: 9000

  mailhog:
    image: druidfi/mailhog:1.0.1
    container_name: "${PREFIX}-mailhog"
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.mailhog.entrypoints: https
      traefik.http.routers.mailhog.rule: Host(`mailhog.${DOCKER_DOMAIN}`,`mailhog.traefik.me`)
      traefik.http.routers.mailhog.tls: "true"
      traefik.http.services.mailhog.loadbalancer.server.port: 8025

  ssh-agent:
    image: "druidfi/ssh-agent:${SSH_IMAGE_VERSION}"
    container_name: "${PREFIX}-ssh-agent"
    restart: unless-stopped
    volumes:
      - ~/.ssh:/ssh
      - ssh:/tmp/druid_ssh-agent/

  catchall:
    image: nginx:stable-alpine
    container_name: "${PREFIX}-catchall"
    restart: unless-stopped
    volumes:
      - ./catchall/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./catchall/index.html:/usr/share/nginx/html/index.html:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.errors.tls: "true"
      traefik.http.routers.errors.priority: 1
      traefik.http.routers.errors.rule: HostRegexp(`{subdomain:[A-Za-z0-9-]+}.${DOCKER_DOMAIN}`,`{subdomain:[A-Za-z0-9-]+}.traefik.me`)

networks:
  default:
    name: "${PREFIX}-network"
    external: true

volumes:
  ssh:
    name: "${PREFIX}-ssh"
    external: true
