version: '3.7'

services:

  app:
    image: ghost:4-alpine
    container_name: ghost-example-app
    depends_on:
      - db
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: ghost
      database__connection__database: ghost
      url: https://ghost.docker.so
    labels:
      traefik.enable: "true"
      traefik.http.routers.ghost-example-app.entrypoints: https
      traefik.http.routers.ghost-example-app.rule: Host(`ghost.docker.so`)
      traefik.http.routers.ghost-example-app.tls: "true"
      traefik.http.services.ghost-example-app.loadbalancer.server.port: 2368
      traefik.docker.network: stonehenge-network
    networks:
      - internal
      - stonehenge-network

  db:
    image: mysql:5.7
    container_name: ghost-example-db
    environment:
      MYSQL_ROOT_PASSWORD: someghost
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghost
    networks:
      - internal

networks:
  internal:
    external: false
  stonehenge-network:
    external: true
