name: Tests

on: [push]

jobs:

  test:

    strategy:
      fail-fast: false
      matrix:
        #os: [ ubuntu-18.04, ubuntu-20.04, macos-latest ]
        os: [ ubuntu-18.04, ubuntu-20.04 ]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Show debug info
        run: |
          make debug
          make ping

      - name: Create test SSH keys
        run: |
          ssh-keygen -q -t rsa -N '' -b 4096 -f ~/.ssh/id_rsa -C "rsa key"
          ssh-keygen -q -t ed25519 -N '' -f ~/.ssh/id_ed25519 -C "ed25519 key"

      - name: Start up Stonehenge
        run: make up

      - name: Ping should resolve to 127.0.0.1 now
        run: make ping

      - name: Check that DNS works when curling Google. Expecting HTTP/2 200
        run: curl -Is https://www.google.com | head -1

      - name: Check if Portainer can be accessed
        run: |
          printf "CURL portainer for checking access starts"
          until curl -s "https://portainer.docker.sh" | grep Portainer; do true; done > /dev/null
          printf "CURL portainer for checking access ends"

      - name: Tear down Stonehenge
        run: make down
